x-postgres-db: &postgres-db
  image: ghcr.io/opexdev/postgres-opex
  environment:
    - POSTGRES_USER=${DB_USER:-opex}
    - POSTGRES_PASSWORD=${DB_PASS:-hiopex}
    - POSTGRES_READ_ONLY_USER=${DB_READ_ONLY_USER:-opex_reader}
    - POSTGRES_READ_ONLY_PASSWORD=${DB_READ_ONLY_PASS:-hiopex}
  networks:
    - default
  deploy:
    restart_policy:
      condition: on-failure

version: '3.8'
services:
  postgres-scanner-scheduler:
    <<: *postgres-db
    volumes:
      - scanner-scheduler-data:/var/lib/postgresql/data/
  postgres-ethereum-scanner:
    <<: *postgres-db
    volumes:
      - ethereum-scanner-data:/var/lib/postgresql/data/
  postgres-bitcoin-scanner:
    <<: *postgres-db
    volumes:
      - bitcoin-scanner-data:/var/lib/postgresql/data/
  postgres-bsc-scanner:
    <<: *postgres-db
    volumes:
      - bsc-scanner-data:/var/lib/postgresql/data/
  postgres-tron-scanner:
    <<: *postgres-db
    volumes:
      - tron-scanner-data:/var/lib/postgresql/data/
  scanner-scheduler:
    image: ghcr.io/opexdev/scanner-scheduler
    environment:
      - JAVA_OPTS=-Xmx768m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DB_IP_PORT=postgres-scanner-scheduler
      - PREFERENCES=$PREFERENCES
    configs:
      - preferences.yml
    depends_on:
      - vault
      - postgres-scanner-scheduler
      - bsc-scanner
    networks:
      - default
  ethereum-scanner:
    image: ghcr.io/opexdev/ethereum-scanner
    environment:
      - JAVA_OPTS=-Xmx768m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DB_IP_PORT=postgres-ethereum-scanner
      - CHAIN_NAME=ethereum
      - RPC_ENDPOINT=${ETH_RPC_ENDPOINT}
      - PREFERENCES=$PREFERENCES
    configs:
      - preferences.yml
    depends_on:
      - vault
      - postgres-ethereum-scanner
    networks:
      - default
  bitcoin-scanner:
    image: ghcr.io/opexdev/bitcoin-scanner
    environment:
      - JAVA_OPTS=-Xmx768m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DB_IP_PORT=postgres-bitcoin-scanner
      - REST_ENDPOINT=${BITCOIN_REST_ENDPOINT}
      - API_KEY=${BITCOIN_API_KEY}
      - PREFERENCES=$PREFERENCES
    configs:
      - preferences.yml
    depends_on:
      - vault
      - postgres-bitcoin-scanner
    networks:
      - default
  bsc-scanner:
    image: ghcr.io/opexdev/ethereum-scanner
    environment:
      - JAVA_OPTS=-Xmx768m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DB_IP_PORT=postgres-bsc-scanner
      - CHAIN_NAME=bsc
      - RPC_ENDPOINT=${BSC_RPC_ENDPOINT}
      - PREFERENCES=$PREFERENCES
    configs:
      - preferences.yml
    depends_on:
      - vault
      - postgres-bsc-scanner
    networks:
      - default
  tron-scanner:
    image: ghcr.io/opexdev/tron-scanner
    environment:
      - JAVA_OPTS=-Xmx768m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DB_IP_PORT=postgres-tron-scanner
      - REST_ENDPOINT=${TRON_REST_ENDPOINT}
      - API_KEY=${TRON_API_KEY}
      - PREFERENCES=$PREFERENCES
    configs:
      - preferences.yml
    depends_on:
      - vault
      - postgres-tron-scanner
    networks:
      - default
volumes:
  scanner-scheduler-data:
  ethereum-scanner-data:
  bitcoin-scanner-data:
  bsc-scanner-data:
  tron-scanner-data:
